DROP DATABASE IF EXISTS unibus;
CREATE DATABASE unibus;
USE unibus;

CREATE TABLE TIMES(
	userID VARCHAR(25) PRIMARY KEY,
	name VARCHAR(200),
	colour VARCHAR(7)
);

---------------------------------------------------------------------------------------------------------------------

CREATE TABLE USERS(
	userID VARCHAR(25) PRIMARY KEY,
	name VARCHAR(200),
	colour VARCHAR(7)
);

CREATE TABLE TEAMS(
	teamID VARCHAR(20) NOT NULL PRIMARY KEY,
	name VARCHAR(20)
);

CREATE TABLE USERTEAMS(
	userID VARCHAR(25) NOT NULL,
	teamID VARCHAR(20),
	verified BOOLEAN,
	isAdmin BOOLEAN,
	hasNotif BOOLEAN,
	FOREIGN KEY (userID) REFERENCES USERS(userID) ON DELETE CASCADE,
	FOREIGN KEY (teamID) REFERENCES TEAMS(teamID) ON DELETE CASCADE,
	UNIQUE (userID,teamID)
);

CREATE TABLE TASKS(
	taskID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	teamID VARCHAR(20),
	name VARCHAR(20),
	details VARCHAR(1000),
	dateSet BIGINT,
	dateDue BIGINT,
	FOREIGN KEY (teamID) REFERENCES TEAMS(teamID) ON DELETE CASCADE
);

CREATE TABLE FILES(
	fileID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	taskID INT,
	name VARCHAR(50),
	url VARCHAR(500),
	FOREIGN KEY (taskID) REFERENCES TASKS(taskID) ON DELETE CASCADE
);

/* 'for schema info abou the messages visit
https://stackoverflow.com/questions/8351526/storing-chat-messages-inside-a-mysql-table'
*/

CREATE TABLE MESSAGE(
	messageID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	messageTime BIGINT,
	messageText TEXT,
	userID VARCHAR(25),
	teamID VARCHAR(30),
	FOREIGN KEY (userID) REFERENCES USERS(userID) ON DELETE CASCADE,
	FOREIGN KEY (teamID) REFERENCES TEAMS(teamID) ON DELETE CASCADE
);

CREATE TABLE USERTASKS(
	PRIMARY KEY (userID,taskID),
	userID VARCHAR(25),
	taskID INT,
	FOREIGN KEY (userID) REFERENCES USERS(userID) ON DELETE CASCADE,
	FOREIGN KEY (taskID) REFERENCES TASKS(taskID) ON DELETE CASCADE
);

CREATE TABLE NOTIFICATIONS(
	notificationID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	notificationName VARCHAR(25),
	details VARCHAR(500),
	teamID VARCHAR(30),
	dateCreated BIGINT,
	FOREIGN KEY (teamID) REFERENCES TEAMS(teamID) ON DELETE CASCADE
);
