DROP DATABASE IF EXISTS unibus;
CREATE DATABASE unibus;
USE unibus;

CREATE TABLE USERS(
	userID VARCHAR(25) PRIMARY KEY,
	name VARCHAR(200),
	colour VARCHAR(7)
);

CREATE TABLE EVENTS(
	userID VARCHAR(25) NOT NULL,
	eventID VARCHAR(25) NOT NULL PRIMARY KEY,
	name VARCHAR(50),
	location VARCHAR(50),
	day VARCHAR(25),
	startTime BIGINT,
	FOREIGN KEY (userID) REFERENCES USERS(userID) ON DELETE CASCADE,
);

CREATE TABLE SETTINGS(
	userID VARCHAR(25) NOT NULL,
	eventID VARCHAR(25) NOT NULL PRIMARY KEY,
	name VARCHAR(50),
	location VARCHAR(50),
	startTime BIGINT,
	FOREIGN KEY (userID) REFERENCES USERS(userID) ON DELETE CASCADE,
);
